version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-235-159-101.compute-1.amazonaws.com
            port: '5432'
            database: d6qeafel8roedm
            ssl: true
            user: bebyzmwubhfcal
            password: 6b249e6feebfa2f3a1033f434d97fbc2ef2d6dd13bda5197a7e5aee58342676a
            migrations: true
